version: '3.8'
services:
  bivrest-in:
    build:
      context: ru
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./ru/xray:/opt/xray/config/
  bivrest-out:
    build:
      context: fr
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1986:1986"
    volumes:
      - ./fr/xray:/opt/xray/config/