version: '3.8'
services:
  bivrest:
    build:
      context: ru
      dockerfile: Dockerfile
    # environment:
    #   - SNI=www.samsung.com
    #   - SHORT_ID=aabbccdd
    restart: always
    ports:
      - "443:443"
    volumes:
      - bivrest-volume:/opt/xray/config
volumes:
  bivrest-volume:
